-- sql/00_raw_stub.sql
-- Create RAW schema and seed minimal source tables for staging models

CREATE DATABASE IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS ANALYTICS.RAW;

USE DATABASE ANALYTICS;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE CUSTOMERS (
  CUSTOMER_ID INT,
  FIRST_NAME STRING,
  LAST_NAME  STRING,
  EMAIL      STRING,
  CITY       STRING,
  STATE      STRING,
  COUNTRY    STRING,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE PRODUCTS (
  PRODUCT_ID INT,
  PRODUCT_NAME STRING,
  CATEGORY     STRING,
  BRAND        STRING,
  UNIT_PRICE   NUMBER(10,2),
  CREATED_AT   TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE ORDERS (
  ORDER_ID     INT,
  CUSTOMER_ID  INT,
  PRODUCT_ID   INT,
  DATE_ID      INT,
  QUANTITY     INT,
  UNIT_PRICE   NUMBER(10,2),
  TOTAL_AMOUNT NUMBER(12,2),
  ORDER_STATUS STRING,
  CREATED_AT   TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE DATE_DIM (
  DATE_ID INT,
  CALENDAR_DATE DATE,
  YEAR INT,
  MONTH INT,
  DAY INT,
  DAY_OF_WEEK STRING,
  IS_WEEKEND BOOLEAN
);

-- Sample data mirroring our analytic demo
INSERT INTO CUSTOMERS VALUES
(1,'Alice','Johnson','alice.johnson@example.com','New York','NY','USA',CURRENT_TIMESTAMP()),
(2,'Bob','Smith','bob.smith@example.com','Chicago','IL','USA',CURRENT_TIMESTAMP()),
(3,'Charlie','Lee','charlie.lee@example.com','San Francisco','CA','USA',CURRENT_TIMESTAMP()),
(4,'Diana','Martinez','diana.martinez@example.com','Miami','FL','USA',CURRENT_TIMESTAMP()),
(5,'Ethan','Wong','ethan.wong@example.com','Seattle','WA','USA',CURRENT_TIMESTAMP());

INSERT INTO PRODUCTS VALUES
(1,'Wireless Mouse','Electronics','LogiTech',29.99,CURRENT_TIMESTAMP()),
(2,'Mechanical Keyboard','Electronics','KeyChron',89.99,CURRENT_TIMESTAMP()),
(3,'Running Shoes','Sportswear','Nike',120.00,CURRENT_TIMESTAMP()),
(4,'Smartphone','Electronics','Apple',999.00,CURRENT_TIMESTAMP()),
(5,'Coffee Maker','Home Appliances','Breville',199.00,CURRENT_TIMESTAMP());

INSERT INTO DATE_DIM VALUES
(1,'2025-08-15',2025,8,15,'Friday',FALSE),
(2,'2025-08-16',2025,8,16,'Saturday',TRUE),
(3,'2025-08-17',2025,8,17,'Sunday',TRUE),
(4,'2025-08-18',2025,8,18,'Monday',FALSE),
(5,'2025-08-19',2025,8,19,'Tuesday',FALSE);

INSERT INTO ORDERS VALUES
(1,1,1,1,2,29.99,59.98,'COMPLETED',CURRENT_TIMESTAMP()),
(2,2,2,2,1,89.99,89.99,'COMPLETED',CURRENT_TIMESTAMP()),
(3,3,3,3,1,120.00,120.00,'COMPLETED',CURRENT_TIMESTAMP()),
(4,4,4,4,1,999.00,999.00,'COMPLETED',CURRENT_TIMESTAMP()),
(5,5,5,5,2,199.00,398.00,'COMPLETED',CURRENT_TIMESTAMP()),
(6,1,3,2,1,120.00,120.00,'COMPLETED',CURRENT_TIMESTAMP()),
(7,2,1,3,3,29.99,89.97,'COMPLETED',CURRENT_TIMESTAMP()),
(8,3,5,4,1,199.00,199.00,'COMPLETED',CURRENT_TIMESTAMP());
