-- sql/01_ddl_snowflake.sql
-- Star schema DDL for Snowflake (ANALYTICS database/schema assumed).

CREATE DATABASE IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS ANALYTICS.PUBLIC;
USE DATABASE ANALYTICS;
USE SCHEMA PUBLIC;

-- Dimensions
CREATE OR REPLACE TABLE DIM_CUSTOMERS (
  CUSTOMER_ID INT AUTOINCREMENT PRIMARY KEY,
  FIRST_NAME STRING NOT NULL,
  LAST_NAME  STRING NOT NULL,
  EMAIL      STRING NOT NULL UNIQUE,
  CITY       STRING,
  STATE      STRING,
  COUNTRY    STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DIM_PRODUCTS (
  PRODUCT_ID  INT AUTOINCREMENT PRIMARY KEY,
  PRODUCT_NAME STRING NOT NULL,
  CATEGORY     STRING,
  BRAND        STRING,
  UNIT_PRICE   NUMBER(10,2) NOT NULL,
  CREATED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DIM_DATE (
  DATE_ID       INT AUTOINCREMENT PRIMARY KEY,
  CALENDAR_DATE DATE NOT NULL,
  YEAR          INT,
  MONTH         INT,
  DAY           INT,
  DAY_OF_WEEK   STRING,
  IS_WEEKEND    BOOLEAN DEFAULT FALSE
);

-- Fact
CREATE OR REPLACE TABLE FACT_ORDERS (
  ORDER_ID     INT AUTOINCREMENT PRIMARY KEY,
  CUSTOMER_ID  INT NOT NULL,
  PRODUCT_ID   INT NOT NULL,
  DATE_ID      INT NOT NULL,
  QUANTITY     INT NOT NULL CHECK (QUANTITY > 0),
  UNIT_PRICE   NUMBER(10,2) NOT NULL CHECK (UNIT_PRICE >= 0),
  TOTAL_AMOUNT NUMBER(12,2) NOT NULL CHECK (TOTAL_AMOUNT = QUANTITY * UNIT_PRICE),
  ORDER_STATUS STRING DEFAULT 'COMPLETED',
  CREATED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES DIM_CUSTOMERS(CUSTOMER_ID),
  FOREIGN KEY (PRODUCT_ID)  REFERENCES DIM_PRODUCTS(PRODUCT_ID),
  FOREIGN KEY (DATE_ID)     REFERENCES DIM_DATE(DATE_ID)
);
